/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Cl_controller_emp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 * @author Carlos Tomás García Martínez 320605
 * @author Uriel Omar González jimenez  320736
 * @author Alejandro Aguirre Baeza      320646
 */ 
public class Cl_gui_emp_update extends javax.swing.JFrame {
    Cl_controller_emp cEmp = new Cl_controller_emp();
    /**
     * Creates new form Cl_gui_emp_insert
     */
    public Cl_gui_emp_update() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblJob = new javax.swing.JLabel();
        lblManagerId = new javax.swing.JLabel();
        lblHireDate = new javax.swing.JLabel();
        lblEmpNo = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lblCommission = new javax.swing.JLabel();
        lblDepartmentId = new javax.swing.JLabel();
        fldEmpNo = new javax.swing.JTextField();
        fldName = new javax.swing.JTextField();
        fldJob = new javax.swing.JTextField();
        fldManagerId = new javax.swing.JTextField();
        fldHireDate = new javax.swing.JTextField();
        fldCommission = new javax.swing.JTextField();
        fldSalary = new javax.swing.JTextField();
        fldDepartmentId = new javax.swing.JTextField();
        btnEmpInsert = new javax.swing.JButton();
        btnSearchEmp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblNewEmployee = new javax.swing.JLabel();
        fldNewEmp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblDeptTittle1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 540));
        setPreferredSize(new java.awt.Dimension(410, 540));
        setResizable(false);

        lblName.setText("Name:");

        lblJob.setText("Job:");

        lblManagerId.setText("Manager id:");

        lblHireDate.setText("Hire date:");

        lblEmpNo.setText("Number of employee");

        lblSalary.setText("Salary:");

        lblCommission.setText("Commission:");

        lblDepartmentId.setText("Department id:");

        fldEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldEmpNoActionPerformed(evt);
            }
        });

        fldJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldJobActionPerformed(evt);
            }
        });

        btnEmpInsert.setBackground(new java.awt.Color(25, 91, 157));
        btnEmpInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpInsert.setText("Update");
        btnEmpInsert.setBorderPainted(false);
        btnEmpInsert.setFocusPainted(false);
        btnEmpInsert.setOpaque(false);
        btnEmpInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpInsertActionPerformed(evt);
            }
        });

        btnSearchEmp.setBackground(new java.awt.Color(238, 227, 95));
        btnSearchEmp.setText("Buscar");
        btnSearchEmp.setBorderPainted(false);
        btnSearchEmp.setFocusPainted(false);
        btnSearchEmp.setOpaque(false);
        btnSearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmpActionPerformed(evt);
            }
        });

        lblNewEmployee.setText("New number of employee");

        fldNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNewEmpActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(77, 77, 77));

        lblDeptTittle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeptTittle1.setForeground(new java.awt.Color(255, 255, 255));
        lblDeptTittle1.setText("Update Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lblDeptTittle1)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeptTittle1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepartmentId)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCommission)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName)
                                            .addComponent(lblNewEmployee)
                                            .addComponent(lblJob)
                                            .addComponent(lblManagerId)
                                            .addComponent(lblHireDate)
                                            .addComponent(lblSalary))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fldCommission, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldSalary, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldHireDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldManagerId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldJob, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldNewEmp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fldDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEmpInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchEmp)
                    .addComponent(lblEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldNewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJob, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpInsert)
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldEmpNoActionPerformed

    private void fldJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldJobActionPerformed

    private void btnSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmpActionPerformed
        ArrayList<String> data;
        data = cEmp.getEmp(Integer.parseInt(fldEmpNo.getText()));
        String newDate = null;
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(data.get(4));
            newDate = new SimpleDateFormat("dd/MM/yyyy").format(date);
        } catch(Exception e) {
            System.out.println(e);
        }
        fldNewEmp.setText(data.get(0));
        fldName.setText(data.get(1));
        fldJob.setText(data.get(2));
        fldManagerId.setText(data.get(3));
        fldHireDate.setText(newDate);
        fldSalary.setText(data.get(5));
        fldCommission.setText(data.get(6));
        fldDepartmentId.setText(data.get(7));
        
    }//GEN-LAST:event_btnSearchEmpActionPerformed

    private void fldNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNewEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNewEmpActionPerformed

    private void btnEmpInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpInsertActionPerformed
        int empId = Integer.parseInt(fldEmpNo.getText()); 
        int newEmpId = Integer.parseInt(fldNewEmp.getText()); 
        String empName = fldName.getText();
        String empJob = fldJob.getText();
        String empHireDate = fldHireDate.getText();
        int empManager = Integer.parseInt(fldManagerId.getText()); 
        int empSalary = Integer.parseInt( fldSalary.getText()); 
        int empCommission = Integer.parseInt(fldCommission.getText()); 
        int empDeptno = Integer.parseInt(fldDepartmentId.getText()); 
        
        cEmp.updateEmp(empId, newEmpId, empName, empJob, empHireDate, empManager, empSalary, empCommission, empDeptno);
        this.dispose();
    }//GEN-LAST:event_btnEmpInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cl_gui_emp_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cl_gui_emp_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cl_gui_emp_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cl_gui_emp_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cl_gui_emp_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpInsert;
    private javax.swing.JButton btnSearchEmp;
    private javax.swing.JTextField fldCommission;
    private javax.swing.JTextField fldDepartmentId;
    private javax.swing.JTextField fldEmpNo;
    private javax.swing.JTextField fldHireDate;
    private javax.swing.JTextField fldJob;
    private javax.swing.JTextField fldManagerId;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextField fldNewEmp;
    private javax.swing.JTextField fldSalary;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCommission;
    private javax.swing.JLabel lblDepartmentId;
    private javax.swing.JLabel lblDeptTittle1;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblHireDate;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel lblManagerId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewEmployee;
    private javax.swing.JLabel lblSalary;
    // End of variables declaration//GEN-END:variables
}
